/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * The backend API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterDto
 */
export interface RegisterDto {
    /**
     * User email address
     * @type {string}
     * @memberof RegisterDto
     */
    email: string;
    /**
     * Unique username for the user
     * @type {string}
     * @memberof RegisterDto
     */
    username: string;
    /**
     * Password (at least 6 characters)
     * @type {string}
     * @memberof RegisterDto
     */
    password: string;
}

/**
 * Check if a given object implements the RegisterDto interface.
 */
export function instanceOfRegisterDto(value: object): value is RegisterDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function RegisterDtoFromJSON(json: any): RegisterDto {
    return RegisterDtoFromJSONTyped(json, false);
}

export function RegisterDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'username': json['username'],
        'password': json['password'],
    };
}

export function RegisterDtoToJSON(json: any): RegisterDto {
    return RegisterDtoToJSONTyped(json, false);
}

export function RegisterDtoToJSONTyped(value?: RegisterDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'username': value['username'],
        'password': value['password'],
    };
}

