/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * My API
 * The backend API description
 * OpenAPI spec version: 1.0
 */

export interface CreateUserDto {
  /** User email address */
  email: string;
  /** Username for the user */
  username: string;
}
