/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * My API
 * The backend API description
 * OpenAPI spec version: 1.0
 */
import type { LoginResponseDtoUser } from './loginResponseDtoUser';

export interface LoginResponseDto {
  accessToken: string;
  user: LoginResponseDtoUser;
}
