/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * My API
 * The backend API description
 * OpenAPI spec version: 1.0
 */

export interface RegisterDto {
  /** User email address */
  email: string;
  /** Unique username for the user */
  username: string;
  /** Password (at least 6 characters) */
  password: string;
  /** Confirm password (at least 6 characters) */
  confirmPassword: string;
}
